package entidades;
// Generated 29/10/2019 03:43:38 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private int idcuenta;
     private Cuenta cuenta;/*esta variable debe inicializarse en el constructor para que en la ejecución
     de la vista no de null pointer, ya que esto no permitira visualizar los datos debido a que se ocupa
     en el arbol donde se ordenan las cuentas*/
     private String nombrecuenta;
     private String descripcioncuenta;
     private String tipocuenta;
     private String codigocuenta;
     private List<Cuenta> cuentinternas = new ArrayList<Cuenta>();
     private Set cuentas = new HashSet(0);
     private Set debehabers = new HashSet(0);

    public Cuenta() {
    }

	
    public Cuenta(int idcuenta) {
        this.idcuenta = idcuenta;
    }
    public Cuenta(int idcuenta, Cuenta cuenta, String nombrecuenta, String descripcioncuenta, String tipocuenta, String codigocuenta, Set cuentas, Set debehabers) {
       this.idcuenta = idcuenta;
       this.cuenta = cuenta;
       this.nombrecuenta = nombrecuenta;
       this.descripcioncuenta = descripcioncuenta;
       this.tipocuenta = tipocuenta;
       this.codigocuenta = codigocuenta;
       this.cuentas = cuentas;
       this.debehabers = debehabers;
    }
    public Cuenta(int idcuenta, String nombrecuenta, String descripcioncuenta, String tipocuenta, String codigocuenta, Cuenta cuenta) {
        this.idcuenta = idcuenta;
        this.nombrecuenta = nombrecuenta;
        this.descripcioncuenta = descripcioncuenta;
        this.tipocuenta = tipocuenta;
        this.codigocuenta = codigocuenta;
        this.cuenta = cuenta;
    }
    
    public Cuenta(int idcuenta, String nombrecuenta, String descripcioncuenta, String tipocuenta, String codigocuenta) {
        this.idcuenta = idcuenta;
        this.nombrecuenta = nombrecuenta;
        this.descripcioncuenta = descripcioncuenta;
        this.tipocuenta = tipocuenta;
        this.codigocuenta = codigocuenta;
    }

    public Cuenta(String nombrecuenta, String descripcioncuenta, String tipocuenta, String codigocuenta, Cuenta cuenta) {
        this.nombrecuenta = nombrecuenta;
        this.descripcioncuenta = descripcioncuenta;
        this.tipocuenta = tipocuenta;
        this.codigocuenta = codigocuenta;
        this.cuenta = cuenta;
    }

    public Cuenta(String nombrecuenta, String descripcioncuenta, String tipocuenta, String codigocuenta) {
        this.nombrecuenta = nombrecuenta;
        this.descripcioncuenta = descripcioncuenta;
        this.tipocuenta = tipocuenta;
        this.codigocuenta = codigocuenta;
    }
   
    public int getIdcuenta() {
        return this.idcuenta;
    }
    
    public void setIdcuenta(int idcuenta) {
        this.idcuenta = idcuenta;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public String getNombrecuenta() {
        return this.nombrecuenta;
    }
    
    public void setNombrecuenta(String nombrecuenta) {
        this.nombrecuenta = nombrecuenta;
    }
    public String getDescripcioncuenta() {
        return this.descripcioncuenta;
    }
    
    public void setDescripcioncuenta(String descripcioncuenta) {
        this.descripcioncuenta = descripcioncuenta;
    }
    public String getTipocuenta() {
        return this.tipocuenta;
    }
    
    public void setTipocuenta(String tipocuenta) {
        this.tipocuenta = tipocuenta;
    }
    public String getCodigocuenta() {
        return this.codigocuenta;
    }
    
    public void setCodigocuenta(String codigocuenta) {
        this.codigocuenta = codigocuenta;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }
    public Set getDebehabers() {
        return this.debehabers;
    }
    
    public void setDebehabers(Set debehabers) {
        this.debehabers = debehabers;
    }

    public List<Cuenta> getCuentinternas() {
        return cuentinternas;
    }

    public void setCuentinternas(List<Cuenta> cuentinternas) {
        this.cuentinternas = cuentinternas;
    }
   
}


