package entidades;
// Generated 29/10/2019 03:43:38 AM by Hibernate Tools 4.3.1



/**
 * Inventario generated by hbm2java
 */
public class Inventario  implements java.io.Serializable {


     private int idinventario;
     private Periodo periodo;
     private String descripcion;
     private String valor;

    public Inventario() {
    }

    public Inventario(Periodo periodo, String descripcion, String valor) {
        this.periodo = periodo;
        this.descripcion = descripcion;
        this.valor = valor;
    }

    public Inventario(String descripcion, String valor) {
        this.descripcion = descripcion;
        this.valor = valor;
    }

	
    public Inventario(int idinventario) {
        this.idinventario = idinventario;
    }
    public Inventario(int idinventario, Periodo periodo, String descripcion, String valor) {
       this.idinventario = idinventario;
       this.periodo = periodo;
       this.descripcion = descripcion;
       this.valor = valor;
    }
   
    public int getIdinventario() {
        return this.idinventario;
    }
    
    public void setIdinventario(int idinventario) {
        this.idinventario = idinventario;
    }
    public Periodo getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Periodo periodo) {
        this.periodo = periodo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


