package entidades;
// Generated 29/10/2019 03:43:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Periodo generated by hbm2java
 */
public class Periodo  implements java.io.Serializable {


     private int idperiodo;
     private Date fechainicial;
     private Date fechafinal;
     private Boolean enproceso;
     private Boolean terminado;
     private Set inventarios = new HashSet(0);
     private Set partidas = new HashSet(0);

    public Periodo() {
    }

	
    public Periodo(int idperiodo) {
        this.idperiodo = idperiodo;
    }
    public Periodo(int idperiodo, Date fechainicial, Date fechafinal, Boolean enproceso, Boolean terminado, Set inventarios, Set partidas) {
       this.idperiodo = idperiodo;
       this.fechainicial = fechainicial;
       this.fechafinal = fechafinal;
       this.enproceso = enproceso;
       this.terminado = terminado;
       this.inventarios = inventarios;
       this.partidas = partidas;
    }

    public Periodo(int idperiodo, Date fechainicial, Date fechafinal, Boolean enproceso, Boolean terminado) {
        this.idperiodo = idperiodo;
        this.fechainicial = fechainicial;
        this.fechafinal = fechafinal;
        this.enproceso = enproceso;
        this.terminado = terminado;
    }

    public Periodo(Date fechainicial, Date fechafinal, Boolean enproceso, Boolean terminado) {
        this.fechainicial = fechainicial;
        this.fechafinal = fechafinal;
        this.enproceso = enproceso;
        this.terminado = terminado;
    }
    
    public int getIdperiodo() {
        return this.idperiodo;
    }
    
    public void setIdperiodo(int idperiodo) {
        this.idperiodo = idperiodo;
    }
    public Date getFechainicial() {
        return this.fechainicial;
    }
    
    public void setFechainicial(Date fechainicial) {
        this.fechainicial = fechainicial;
    }
    public Date getFechafinal() {
        return this.fechafinal;
    }
    
    public void setFechafinal(Date fechafinal) {
        this.fechafinal = fechafinal;
    }
    public Boolean getEnproceso() {
        return this.enproceso;
    }
    
    public void setEnproceso(Boolean enproceso) {
        this.enproceso = enproceso;
    }
    public Boolean getTerminado() {
        return this.terminado;
    }
    
    public void setTerminado(Boolean terminado) {
        this.terminado = terminado;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }
    public Set getPartidas() {
        return this.partidas;
    }
    
    public void setPartidas(Set partidas) {
        this.partidas = partidas;
    }




}


